name: Comment Moderation

on:
  discussion_comment:
    types: [created]
  discussions:
    types: [created]

jobs:
  moderate-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check for inappropriate content
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const inappropriateWords = ['垃圾', '废物', '傻逼', 'fuck', 'shit']; // 添加需要过滤的词汇
            
            let content = '';
            if (context.eventName === 'discussion_comment') {
              content = context.payload.comment.body;
            } else if (context.eventName === 'discussions') {
              content = context.payload.discussion.body;
            }
            
            const hasInappropriateContent = inappropriateWords.some(word => 
              content.toLowerCase().includes(word.toLowerCase())
            );
            
            if (hasInappropriateContent) {
              console.log('发现不当内容，已隐藏');
              // 这里可以添加隐藏或删除评论的逻辑
            }
